- clean: ['~', '~/.config']

- link:
    ~/.agignore: agignore
    ~/.axelrc: axelrc
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.hgrc: hgrc
    ~/.inputrc: inputrc
    ~/.rtorrent.rc: rtorrent.rc
    ~/.sbt/0.13/build.sbt:
      create: true
      path: sbt/0.13/build.sbt
    ~/.sbt/0.13/plugins/plugins.sbt:
      create: true
      path: sbt/0.13/plugins/plugins.sbt
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

- shell:
  - mkdir -p ~/.rtorrent/{session,watch,downloads}
  - git update-submodules # after linking ~/.gitconfig
