- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore: agignore
    ~/.axelrc: axelrc
    ~/.config/nvim/bundle: vim/bundle
    ~/.config/nvim/ftplugin: vim/ftplugin
    ~/.config/nvim/init.vim: vimrc
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gnupg/gpg.conf: gpg.conf
    ~/.hgrc: hgrc
    ~/.inputrc: inputrc
    ~/.rtorrent.rc: rtorrent.rc
    ~/.sbt/0.13/build.sbt: sbt/0.13/build.sbt
    ~/.sbt/0.13/plugins/plugins.sbt: sbt/0.13/plugins/plugins.sbt
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zsh: zsh
    ~/.zshrc: zshrc

- shell:
  - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - git update-submodules # after linking ~/.gitconfig
