- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore: agignore
    ~/.aria2/aria2.conf: aria2.conf
    ~/.axelrc: axelrc
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gnupg/gpg.conf: gpg.conf
    ~/.hgrc: hgrc
    ~/.inputrc: inputrc
    ~/.rtorrent.rc: rtorrent.rc
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zsh: zsh
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.bash: bash
    ~/.config/terminator: config/terminator

- shell:
  - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - git update-submodules # after linking ~/.gitconfig
  - ~/.dotfiles/zsh/oh-my-zsh.zsh 
  - ~/.dotfiles/gnome-terminal-colors-solarized/install.sh --scheme dark --profile Solarized && echo "Make 'Solarized' profile first"
  - ~/.dotfiles/oh-my-zsh-install.sh
  #- ~/.dotfiles/gnome-terminal-colors-solarized/install.sh
  #- /home/fsabado/dotfiles/oh-my-zsh/tools
