[[snippets]]
  description = "Manual"
  command = "man <command>"
  output = ""

[[snippets]]
  description = "Display directory contents.-l (long listing) -a (all)"
  command = "ls -al"
  output = ""

[[snippets]]
  description = "List Block Devices (lsblk). -l (list)"
  command = "lsblk"
  output = ""

[[snippets]]
  description = "Check MD5 Checksum"
  command = "md5sum <filename>"
  output = ""

[[snippets]]
  description = "Unix Name. Print detailed information about machine. -a (all)"
  command = "uname -a"
  output = ""

[[snippets]]
  description = "History (Event) Record. Print history of executed command on terminal.'Ctrl + R' to search history"
  command = "history"
  output = ""

[[snippets]]
  description = "Clear terminal"
  command = "clear terminal"
  output = ""

[[snippets]]
  description = "Super user do. (sudo). Execute command as super user or other user."
  command = "sudo <command>"
  output = ""

[[snippets]]
  description = "Make directory (mkdir). Create directory. -p (create hierarchy)"
  command = "mkdir <directory>"
  output = ""

[[snippets]]
  description = "Remove directory (rmdir)"
  command = "rmdir <directory>"
  output = ""

[[snippets]]
  description = "Remove file. -r (recursive), -f (force)"
  command = "rm <filename>"
  output = ""

[[snippets]]
  description = "Touch updates access and modification time of file. Create if nonexistent"
  command = "touch <filename>"
  output = ""

[[snippets]]
  description = "Change file mode bits (chmod). Changes permissions. Read (r)=4,Write(w)=2,Execute(x)=1"
  command = "chmod <accessbits> <filename>"
  output = ""

[[snippets]]
  description = "Change file owner and group (chown). Change group|user ownership"
  command = "chown <user>:<group> <filename>"
  output = ""

[[snippets]]
  description = "Package manager. Debian (apt). Redhat (yum)"
  command = "yum"
  output = ""

[[snippets]]
  description = "Tape Archive (tar). Create|extract archive. (-xvf : default extract) c – create,x - extract,t - list,r - append, C - tar to directory, v – verbose,f – filename, z - create gzip, j - create bz2. Source:https://www.tecmint.com/18-tar-command-examples-in-linux/"
  command = "tar <options> archive1 archive2"
  output = ""

[[snippets]]
  description = "Calendar"
  command = "cal"
  output = ""

[[snippets]]
  description = "Date"
  command = "date"
  output = ""

[[snippets]]
  description = "Concatenation (cat). Two or more files print contents to standard output"
  command = "cat <file1> <file2>"
  output = ""

[[snippets]]
  description = "Copy"
  command = "cp <filename> <directory>"
  output = ""

[[snippets]]
  description = "Move from one location to another"
  command = "mv <file> <directory>"
  output = ""

[[snippets]]
  description = "Print working directory"
  command = "pwd"
  output = ""

[[snippets]]
  description = "Change directory (cd)"
  command = "cd <directory>"
  output = ""

[[snippets]]
  description = "Search recursively all files for a string."
  command = "grep -r \"word\" ."
  output = ""

[[snippets]]
  description = "Search recursively all files for a string, ignoring case."
  command = "grep -ri \"word\" ."
  output = ""

[[snippets]]
  description = "List all the apps installed on the system."
  command = "for app in /usr/share/applications/*.desktop ~/.local/share/applications/*.desktop; do app=\"${app##/*/}\"; echo \"${app::-8}\"; done"
  output = ""

[[snippets]]
  description = "Create a ssh key using RSA."
  command = "ssh keygen -t rsa"
  output = ""

[[snippets]]
  description = "Add public ssh key to a remote server in one command."
  command = "cat ~/.ssh/id_rsa.pub | ssh user@host \"cat - >> ~/.ssh/authorized_keys\""
  output = ""

[[snippets]]
  description = "Get ip of the host. Modify the host name."
  command = "getent hosts <hostname> | awk '{ print $1 }'"
  output = ""

[[snippets]]
  description = "Start docker daemon"
  command = "sudo service docker start"
  output = ""

[[snippets]]
  description = "Check status of docker daemon."
  command = "sudo service docker status"
  output = ""

[[snippets]]
  description = "Stop docker daemon."
  command = "sudo service docker stop"
  output = ""

[[snippets]]
  description = "Add a linux user to a group."
  command = "sudo usermode -aG <group> <username>"
  output = ""

[[snippets]]
  description = "Fetch all pods in all namespaces."
  command = "kubetctl get pods --all-namespaces"
  output = ""

[[snippets]]
  description = "Git overwrite local files to the latest on origin."
  command = "git fetch --all; git reset --hard origin/master"
  output = ""

[[snippets]]
  description = "Git: revert or restore files."
  command = "git checkout develop -- file/to/restore file2/to/restore"
  output = ""

[[snippets]]
  description = "Mount network share folder"
  command = "sudo mount -t cifs //network/share /share -o user=$(whoami)"
  output = ""

[[snippets]]
  description = "id -u <username>"
  command = "Get user UID"
  output = ""

[[snippets]]
  description = "id -g <username>"
  command = "get user group ID - GID"
  output = ""

[[snippets]]
  description = "Show storage devices in human readable format."
  command = "df -H"
  output = ""

[[snippets]]
  description = "Add user to wheel group to allow sudo access."
  command = "usermod -aG wheel <username> #assumed on root"
  output = ""

[[snippets]]
  description = "Find a file in a directory. -iname for case insensitive. -type f (file) -type d (directory). -delete the files found"
  command = "find <directory> -type f -name \"<filename>\""
  output = ""

[[snippets]]
  description = "Find a file in a directory that contains text"
  command = "find . -type f -print | xargs grep \"example\""
  output = ""

[[snippets]]
  description = "Nvidia Graphics Card information"
  command = "nvidia-smi"
  output = "nvidia-smi"

[[snippets]]
  description = "Git clone with specific folder name or directory. Can also use . to denote current directory."
  command = "git clone git@github.com:whatever <foldername>"
  output = ""

[[snippets]]
  description = "Git pull all submodule."
  command = "git submodule update --init --recursive"
  output = ""

[[snippets]]
  description = "Disc usage (du). Command estimates <filepath> space usage. -s (summarize), -h (human-readable, -c --total"
  command = "du -sh <filepath>"
  output = ""

[[snippets]]
  description = "Rsync - fast,versatile, remote (and local) file-copying tool."
  command = "rsync -a -v --ignore-existing <src> <dst>"
  output = ""

[[snippets]]
  description = "Check all mounted locations."
  command = "sudo cat /proc/mounts"
  output = "sudo cat /proc/mounts"

[[snippets]]
  description = "[Redhat]Install 'yum-versionlock'. Will not allow to upgrade the Agent package to version greater than what was installed at the time the locking was performed. Allowed commands: add/exclude/list/delete/clear. Edit List: /etc/yum/pluginconf.d/versionlock.list. Example: # yum versionlock datastax-agent-5.2.5"
  command = "yum versionlock add <package-wildcard>"
  output = ""

[[snippets]]
  description = "The lscpu command reports information about the cpu and processing units. It does not have any further options or functionality. Hardware information.  "
  command = "lscpu"
  output = ""


[[snippets]]
  description = "[lshw] A general purpose utility, that reports detailed and brief information about multiple different hardware units such as cpu, memory, disk, usb controllers, network adapters etc. Lshw extracts the information from different /proc files. Req. sudo. "
  command = "sudo lshw -short"
  output = ""

[[snippets]]
  description = "[lspci] The lspci command lists out all the pci buses and details about the devices connected to them. The vga adapter, graphics card, network adapter, usb ports, sata controllers, etc all fall under this category. "
  command = "lspci"
  output = ""

[[snippets]]
  description = "Download rpms using yum along with all its dependencies (at working directory). Install yum-utils."
  command = "yumdownloader --resolve <package-name>"
  output = ""

[[snippets]]
  description = "Install RPM files."
  command = "rpm -ivh <rpm-files>"
  output = ""


